Inspect the Data

In [1]:
import pandas as pd
import numpy as np

In [2]:

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)

In [3]:
print(df.head())

   patient_id   age weight  blood_pressure  medication insurance_provider
0         101    25     70           120.0     Aspirin         Blue Cross
1         102    34     65           130.0   Metformin              Aetna
2         103  None     80             NaN  Lisinopril              Cigna
3         104    45   None           140.0        None       UnitedHealth
4         105    29     75           125.0     Aspirin               None

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

From th above info(), it is clearly noted that except patient_id rest of the column has Null values. <br>Also, only Patient_id and blood_pressure column has Numerical datas as noted.

In [5]:
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [6]:
print(f"Percentage of missing values:\n{(df.isnull().sum()/len(df))*100}")

Percentage of missing values:
patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

In [7]:
print(f"Number of duplicate rows in df:\n{df.duplicated().sum()}\n")

Number of duplicate rows in df:
2

Data Type Conversion

In [8]:
new_df = df.copy()

In [9]:

new_df['age'] = pd.to_numeric(new_df['age'], errors = 'coerce')

print(f"Find the data types change in the age column: {new_df.dtypes}")

Find the data types change in the age column: patient_id              int64
age                   float64
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

In [10]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 16 non-null     float64
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

In [11]:
new_df['weight'] = pd.to_numeric(new_df['weight'], errors= 'coerce')
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 16 non-null     float64
 2   weight              15 non-null     float64
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 1.1+ KB

In [12]:
print(f"Number of null values in df:\n{df.isnull().sum()}\n")
print(f"Number of null values in new_df:\n{new_df.isnull().sum()}")

Number of null values in df:
patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

Number of null values in new_df:
patient_id            0
age                   4
weight                5
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

In [13]:
Null_count = df['age'].isnull().sum() + df['weight'].isnull().sum()
New_null_count = new_df['age'].isnull().sum() + new_df['weight'].isnull().sum()
print(Null_count)
print(New_null_count)
if Null_count != New_null_count:
    print(f"The number of missing values has changed after converting to numeric :{New_null_count - Null_count}")

7
9
The number of missing values has changed after converting to numeric :2

In [14]:
new_df['insurance_provider'].astype('category').info()

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: insurance_provider
Non-Null Count  Dtype
--------------  -----
17 non-null     category
dtypes: category(1)
memory usage: 356.0 bytes

In [15]:
print(new_df.dtypes)

patient_id              int64
age                   float64
weight                float64
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

Tassk 3: Handle Missing Values

In [16]:
new_df['age'] = new_df['age'].fillna(new_df['age'].median())
new_df.head()

   patient_id   age  weight  blood_pressure  medication insurance_provider
0         101  25.0    70.0           120.0     Aspirin         Blue Cross
1         102  34.0    65.0           130.0   Metformin              Aetna
2         103  34.5    80.0             NaN  Lisinopril              Cigna
3         104  45.0     NaN           140.0        None       UnitedHealth
4         105  29.0    75.0           125.0     Aspirin               None

In [17]:
new_df['weight'] = new_df['weight'].fillna(new_df['weight'].median())
new_df.head()

   patient_id   age  weight  blood_pressure  medication insurance_provider
0         101  25.0    70.0           120.0     Aspirin         Blue Cross
1         102  34.0    65.0           130.0   Metformin              Aetna
2         103  34.5    80.0             NaN  Lisinopril              Cigna
3         104  45.0    74.0           140.0        None       UnitedHealth
4         105  29.0    75.0           125.0     Aspirin               None

In [18]:
new_df['blood_pressure'] = new_df['blood_pressure'].fillna(new_df['blood_pressure'].median())
new_df.head()

   patient_id   age  weight  blood_pressure  medication insurance_provider
0         101  25.0    70.0           120.0     Aspirin         Blue Cross
1         102  34.0    65.0           130.0   Metformin              Aetna
2         103  34.5    80.0           129.0  Lisinopril              Cigna
3         104  45.0    74.0           140.0        None       UnitedHealth
4         105  29.0    75.0           125.0     Aspirin               None

In [19]:
new_df['medication'] = new_df['medication'].fillna(new_df['medication'].mode()[0])
new_df.head()

   patient_id   age  weight  blood_pressure  medication insurance_provider
0         101  25.0    70.0           120.0     Aspirin         Blue Cross
1         102  34.0    65.0           130.0   Metformin              Aetna
2         103  34.5    80.0           129.0  Lisinopril              Cigna
3         104  45.0    74.0           140.0     Aspirin       UnitedHealth
4         105  29.0    75.0           125.0     Aspirin               None

In [20]:
new_df['insurance_provider'] = new_df['insurance_provider'].fillna('Unknown')
new_df.head()

   patient_id   age  weight  blood_pressure  medication insurance_provider
0         101  25.0    70.0           120.0     Aspirin         Blue Cross
1         102  34.0    65.0           130.0   Metformin              Aetna
2         103  34.5    80.0           129.0  Lisinopril              Cigna
3         104  45.0    74.0           140.0     Aspirin       UnitedHealth
4         105  29.0    75.0           125.0     Aspirin            Unknown

Task  4: Handle Duplicates

In [21]:
print(new_df[new_df.duplicated(keep = False)])

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

In [22]:
print(new_df.duplicated(subset=['patient_id']))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17    False
18    False
19    False
dtype: bool

In [23]:
new_df = new_df.drop_duplicates(subset='patient_id', keep='first')

In [24]:
print(f"The shape of the original dataframe: {df.shape}")
print(f"The shape of the original dataframe: {new_df.shape}")

The shape of the original dataframe: (20, 6)
The shape of the original dataframe: (18, 6)

Task 5 : Complete Workflow with Verfication

In [25]:
print("=============   Verfication Report  =============")
print("\t\t\tOriginal DataFrame\t\tCleaned DataFrame\t")
print(f"Shape\t\t\t{df.shape}\t\t\t\t{new_df.shape}")
print(f"Missing Values\t\t\t{Null_count}\t\t\t\t{New_null_count}")
print(f"Duplicate Rows\t\t\t{df.duplicated().sum()}\t\t\t\t{new_df.duplicated().sum()}")
print(f"Data Types: Original DataFrame \n{df.dtypes}\t\t\n\nData Types: Original DataFrame\n{new_df.dtypes}")

=============   Verfication Report  =============
			Original DataFrame		Cleaned DataFrame
Shape			(20, 6)				(18, 6)
Missing Values			7				9
Duplicate Rows			2				0
Data Types: Original DataFrame
patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

Data Types: Original DataFrame
patient_id              int64
age                   float64
weight                float64
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object