In [1]:
import pandas as pd

In [2]:
pd.Series([10, 20, 'Alice', 40.0, 'Bob']) # This will print the series object with default index.

0       10
1       20
2    Alice
3     40.0
4      Bob
dtype: object

In [3]:
Marks = pd.Series([10, 20, 30,40,50])
Marks # This will print the series object with default index starting from 0 to 4 along with the dtype of the data.

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
Marks = pd.Series([98, 85, 92, 78,88], index = ["Maths", "Science", "English", "Tamil", "Social_Science"])
Marks

Maths             98
Science           85
English           92
Tamil             78
Social_Science    88
dtype: int64

In [21]:
Marks.index

Index(['Maths', 'Science', 'English', 'Tamil', 'Social_Science'], dtype='object')

In [ ]:
data = { 'Name': ['Ali', 'Bobe', 'Charl', 'Davi', 'Ele'],
         'Age': [25, 30, 35, 55, 45],
         'City': ['Chennai', 'Bangalore', 'Hyderabad', 'Delhi', 'Mumbai'] }
pd.DataFrame(data)

    Name  Age       City
0    Ali   25    Chennai
1   Bobe   30  Bangalore
2  Charl   35  Hyderabad
3   Davi   55      Delhi
4    Ele   45     Mumbai

In [5]:
raw_data = """Name,Age,City
Ali,25,Chennai
Bobe,30,Bangalore
Charl,35,Hyderabad
Davi,55,Delhi
Ele,45,Mumbai"""
with open("Raw_data.csv", "w")as f:
    f.write(raw_data)

df =pd.read_csv("Raw_data.csv")
df

    Name  Age       City
0    Ali   25    Chennai
1   Bobe   30  Bangalore
2  Charl   35  Hyderabad
3   Davi   55      Delhi
4    Ele   45     Mumbai

In [12]:
df = pd.DataFrame(data)
print(df)

    Name  Age       City
0    Ali   25    Chennai
1   Bobe   30  Bangalore
2  Charl   35  Hyderabad
3   Davi   55      Delhi
4    Ele   45     Mumbai

In [14]:
df.head(3)

    Name  Age       City
0    Ali   25    Chennai
1   Bobe   30  Bangalore
2  Charl   35  Hyderabad

In [18]:
df.tail(2)

   Name  Age    City
3  Davi   55   Delhi
4   Ele   45  Mumbai

In [ ]:
df.shape

(5, 3)

In [19]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
new_column = ['Tamil_Nadu', 'Karnataka', 'Telangana', 'Delhi', 'Maharashtra']
df['State'] = new_column
df

    Name  Age       City        State
0    Ali   25    Chennai   Tamil_Nadu
1   Bobe   30  Bangalore    Karnataka
2  Charl   35  Hyderabad    Telangana
3   Davi   55      Delhi        Delhi
4    Ele   45     Mumbai  Maharashtra

In [ ]:
#Other ways to append a column to the dataframe
df['State'] = ['Tamil_Nadu', 'Karnataka', 'Telangana', 'Delhi', 'Maharashtra']
new_column = {'States': ['Tamil_Nadu', 'Karnataka', 'Telangana', 'Delhi', 'Maharashtra']}
df = df.assign(**new_column)
df

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [8]:
print(df.describe())

             Age
count   5.000000
mean   38.000000
std    12.041595
min    25.000000
25%    30.000000
50%    35.000000
75%    45.000000
max    55.000000

In [ ]:
print(df["Age"]) #Output is in Series instead Dataframe as we called just a single column, so Pandas optimised the output to Series!

0    25
1    30
2    35
3    55
4    45
Name: Age, dtype: int64

In [16]:
print(df["Age"].mean())

38.0

In [14]:
print(df[["Age"]]) #Here find difference in output, it is displayed as Dataframe

   Age
0   25
1   30
2   35
3   55
4   45

In [17]:
print(df[["Name", "Age"]])

    Name  Age
0    Ali   25
1   Bobe   30
2  Charl   35
3   Davi   55
4    Ele   45

In [21]:
print(df['Age']>35)
print(df[df['Age']>35])

0    False
1    False
2    False
3     True
4     True
Name: Age, dtype: bool
   Name  Age    City
3  Davi   55   Delhi
4   Ele   45  Mumbai

In [27]:
print(df[(df["Age"]>25) & (df["Age"]<= 35)])

    Name  Age       City
1   Bobe   30  Bangalore
2  Charl   35  Hyderabad