Name: Vijaya Mohan <br>
Roll Number: IITP_AIMLTN_2602502 <br>
Assignment: Pandas - Question 1

Let's import Pandas library as 'pd'(Though alias naming is optional but it's convinent and great practice! )

In [1]:
import pandas as pd

Creating a 2 Dimensional data (Table) using dictionary and saving the data in DataFrame for later use.

In [2]:
students = {"StudentID" : [101,102,103,104,105,106,107,108,109,110],
            "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ivan", "Julia"],
            "Age": [20,21,19,22,20,21,23,19,22,20],
            "Marks": [88,75,92,65,78,85,70,95,60,80]
            }
df = pd.DataFrame(students)
print(df)

   StudentID     Name  Age  Marks
0        101    Alice   20     88
1        102      Bob   21     75
2        103  Charlie   19     92
3        104    Diana   22     65
4        105    Ethan   20     78
5        106    Fiona   21     85
6        107   George   23     70
7        108   Hannah   19     95
8        109     Ivan   22     60
9        110    Julia   20     80

Saving the DataFrame to a CSV file named "students.csv" without the index column, here I located the file in the current working directory(You can specify a different path if needed.)

In [7]:
df.to_csv("students.csv", index=False)

Let's read the students.csv file and load into a new dataframe.

In [3]:
new_df = pd.read_csv("students.csv")
print(new_df)

   StudentID     Name  Age  Marks
0        101    Alice   20     88
1        102      Bob   21     75
2        103  Charlie   19     92
3        104    Diana   22     65
4        105    Ethan   20     78
5        106    Fiona   21     85
6        107   George   23     70
7        108   Hannah   19     95
8        109     Ivan   22     60
9        110    Julia   20     80

In order to view the first 3 rows from the entire DataFrame we can make use of DataFrame_name.head(<Number of Rows>) method.(By default head() will give 5 rows)

In [4]:
new_df.head(3)

   StudentID     Name  Age  Marks
0        101    Alice   20     88
1        102      Bob   21     75
2        103  Charlie   19     92

DataFrame_name.describe() ->  If in case you need to perform statistical functions such as count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values for each numerical column in the DataFrame, describe() method is all in one go.(One of the best use case is Data Analytics)

In [5]:
new_df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

Instead of counting each rows and columns in Big data, shape property will give number of Rows and columns in 'tuple'

In [6]:
new_df.shape

(10, 4)

Before processing the data knowing the datatype of each column is efficient, can be done using dtypes property.

In [7]:
new_df.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
dtype: object

info() method give information about the Dataframes's index name, data types and information about the Outliers (Null values) <br>
Will gives you the Non-Null values count in each column, which will be the first step in the Data Cleaning Process!

In [8]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes